apiVersion: v1
kind: Service
metadata:
  name: consumer-diff-headless
spec:
  clusterIP: None  # Headless Service
  selector:
    app: consumer-diff
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer-diff
  labels:
    app: consumer-diff
spec:
  hostname: consumer-diff
  subdomain: consumer-diff-headless  # Headless service와 연결
  nodeSelector:
    kubernetes.io/hostname: rubikpi  # Fixed consumer node
  containers:
  - name: consumer
    image: ssoonan0770/jitter-consumer:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: LISTEN_PORT
      value: "8080"
    resources:
      requests:
        cpu: "1"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "256Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: producer-diff
  labels:
    app: producer-diff
spec:
  nodeSelector:
    kubernetes.io/hostname: PRODUCER_NODE_PLACEHOLDER
  containers:
  - name: producer
    image: ssoonan0770/jitter-producer:latest
    imagePullPolicy: Always
    env:
    - name: TARGET_ADDRESS
      value: "consumer-diff.consumer-diff-headless.default.svc.cluster.local:8080"  # 전체 DNS 이름
    - name: SEND_INTERVAL_MS
      value: "10"
    resources:
      requests:
        cpu: "1"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "256Mi"