apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: consumer-svc
  labels:
    app: consumer
spec:
  nodeSelector:
    kubernetes.io/hostname: NODE_NAME_PLACEHOLDER
  containers:
    - name: consumer
      image: ssoonan0770/jitter-consumer:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: LISTEN_PORT
          value: "8080"
      resources:
        requests:
          cpu: "1"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "256Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: producer-svc
  labels:
    app: producer
spec:
  nodeSelector:
    kubernetes.io/hostname: NODE_NAME_PLACEHOLDER
  containers:
    - name: producer
      image: ssoonan0770/jitter-producer:latest
      imagePullPolicy: Always
      env:
        - name: TARGET_ADDRESS
          value: "consumer-service:8080" # Service 이름 사용
        - name: SEND_INTERVAL_MS
          value: "10"
      resources:
        requests:
          cpu: "1"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "256Mi"
